import type { Content } from "pdfmake/interfaces";
import { requireApiRole } from "@/lib/auth";
import { apiError } from "@/lib/api";
import { pdf } from "@/lib/report-response";
import { buildPdf, dataTable, sectionTitle } from "@/lib/pdf";
import { buildManufacturerPerformance, fleetAverage } from "@/lib/manufacturer-performance";
import { ROLE_LABELS } from "@/lib/format";

/**
 * GET /api/pdf/manufacturer-performance — the comparison table, boardroom-ready.
 */
export async function GET() {
  try {
    const viewer = await requireApiRole("ADMIN", "MANAGER");
    const rows = await buildManufacturerPerformance();
    const avgFailureRate = fleetAverage(rows, "failureRatePct");

    const content: Content[] = [];

    content.push(sectionTitle("Manufacturer comparison — worst failure rate first"));
    content.push({
      text: `Fleet-average failure rate: ${avgFailureRate != null ? avgFailureRate.toFixed(1) + "%" : "not available"}. A manufacturer above this line is underperforming the fleet as a whole.`,
      style: "muted", margin: [0, 0, 0, 10],
    });
    content.push(dataTable(
      ["Manufacturer", "Country", "Units", "Failure %", "Service life (yr)", "Claims filed", "Settled", "Disputed", "Most common fault", "IR decline/yr", "BDV decline/yr"],
      rows.map((r) => [
        r.name, r.country ?? "—", r.unitsInFleet,
        r.failureRatePct != null ? `${r.failureRatePct.toFixed(1)}%` : "—",
        r.avgServiceLifeYears != null ? r.avgServiceLifeYears.toFixed(1) : "—",
        r.warrantyClaimsFiled, r.claimsSettled, r.claimsDisputed,
        r.mostCommonFault ?? "—",
        r.avgIrDeclinePerYearMohm != null ? r.avgIrDeclinePerYearMohm.toFixed(2) : "—",
        r.avgBdvDeclinePerYearKv != null ? r.avgBdvDeclinePerYearKv.toFixed(2) : "—",
      ]),
      ["auto", "auto", "auto", "auto", "auto", "auto", "auto", "auto", "*", "auto", "auto"],
      (row) => {
        const pct = row[3] === "—" ? null : parseFloat(String(row[3]));
        return pct != null && avgFailureRate != null && pct > avgFailureRate ? "#fee2e2" : undefined;
      },
    ));

    content.push({
      margin: [0, 12, 0, 0],
      text:
        "Failure rate is the share of a manufacturer's units with at least one recorded fault. Service life is years " +
        "from installation to retirement, or years in service so far for active units. IR/BDV decline compares each " +
        "unit's first and last test and averages the rate across units with at least two tests — positive means " +
        "declining, which is the direction that predicts failure.",
      style: "muted",
    });

    const buffer = await buildPdf({
      cover: {
        title: "Manufacturer Performance Report",
        headline: "Manufacturer Comparison",
        subhead: `${rows.length} manufacturers`,
        meta: [
          ["Fleet avg failure rate", avgFailureRate != null ? `${avgFailureRate.toFixed(1)}%` : "—"],
          ["Generated by", `${viewer.name} (${ROLE_LABELS[viewer.role]})`],
          ["Date", new Date().toLocaleString("en-GB")],
        ],
      },
      content,
      landscape: true,
    });

    return pdf(buffer, "manufacturer-performance");
  } catch (error) {
    return apiError(error);
  }
}
